### ISSUE TITLE
Ability to add percentages for height and width

### ISSUE THREAD

**Issue by julzmon** [josephfusco/angled-edges#8]
First of thanks for the great mixin. I would like to request ability to use percentages or other measurements for height and width of the SVG image.

**Comment by josephfusco** [comment]
Thanks!

In regards to percentages, I am all for it as it would be a game changer for this mixin and great addition for next release. I have yet to come up with a way to build the shape without a fixed unit like pixels but know it is doable. I think we would have to just restructure the svg attributes in the mixin before it is encoded.

**Comment by nlemoine** [comment]
Not using the same approach but might be useful: https://www.sitepoint.com/tilted-angles-in-sass/

**Comment by josephfusco** [comment]
Just released version 2.0 which adds a default of 100% width to the svg image!

See [Upgrading from 1.x](https://github.com/josephfusco/angled-edges/blob/master/README.md#upgrading-from-1x).

While this update does not fully support different length types or a percentage height, I am going to close this issue since I feel this covers the broader goal of what a lot of people have been asking about wanting the shape to be 100% of the container instead of having only fixed widths.

**Comment by Timoti** [comment]
Working beautifully - thanks Joseph for all your work on this.
